name: Windows

on:
  push:
  pull_request:
  schedule:
  - cron: '0 8 * * 2' # At 08:00 on Tuesday (https://crontab.guru/#0_8_*_*_2)
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false

# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  CTEST_PARALLEL_LEVEL: 2
  CTEST_OUTPUT_ON_FAILURE: 1
  CMAKE_BUILD_TYPE: Release
  CXXFLAGS: "/W3 /Ox /arch:AVX2"
  PB_NATIVE_SIMD: OFF

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Requirements
        run: pip install matplotlib numpy pytest scipy setuptools wheel

      - name: Configure
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake -S . -B build/ -G "Visual Studio 16 2019" ^
              -DPB_WERROR=ON -DPB_NATIVE_SIMD=${{ env.PB_NATIVE_SIMD }} ^
              -DPython3_FIND_REGISTRY=LAST ^
              -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }}

      - name: Build
        run: cmake --build build/ --config ${{ env.CMAKE_BUILD_TYPE }}

      #- name: Tests
      #  run: cmake --build . --target tests --config ${{ env.CMAKE_BUILD_TYPE }}
      #  working-directory: build/

      - name: Deploy
        run: |
          python setup.py bdist_wheel
          # twine upload -u $env:PYPI_USER -p $env:PYPI_PASS --skip-existing dist\*.whl

      - name: Run debugging session in tmate
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled && always()
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - uses: actions/upload-artifact@v3
        with:
          name: pybinding-windows-wheel
          path: dist/*.whl
